name: composer update

on:
  schedule:
    - cron: '0 0 1 * *' #UTC, day 1 every month

jobs:
  composer_update_job:
    runs-on: ubuntu-latest
    name: composer update
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: composer update action
        uses: kawax/composer-update-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}